Repository googleapis/python-automl, pull requests merged in 2022-04, with the labels that each got.

#355 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  docs/conf.py
  google/cloud/automl_v1/gapic/prediction_service_client.py
  google/cloud/automl_v1/proto/prediction_service_pb2_grpc.py
  google/cloud/automl_v1/proto/service_pb2_grpc.py
  google/cloud/automl_v1beta1/gapic/prediction_service_client.py
  google/cloud/automl_v1beta1/proto/prediction_service_pb2_grpc.py
  google/cloud/automl_v1beta1/proto/service_pb2_grpc.py
  google/cloud/automl_v1beta1/tables/tables_client.py
  noxfile.py
  setup.py
Labels: api: automl, automerge, size: l

#367 chore: allow releases from previous version branches
  .github/release-please.yml
  owlbot.py
Labels: api: automl, size: s

#369 chore: update README to link to the Vertex AI migration guide
  README.rst
Labels: api: automl, size: xs

#370 chore: format update to README.rst
  README.rst
Labels: api: automl, size: xs
